const DB_NAME = "quickshare";

const SNIPPET_EXPIRY_MIN = 5;
const SNIPPET_EXPIRY_MAX = 30;
const SNIPPET_EXPIRY_DEFAULT = 15;
const SNIPPET_CONTENT_MAX_LENGTH = 50000;
const SNIPPET_TITLE_MAX_LENGTH = 100;
const SNIPPET_ID_LENGTH = 8;

module.exports = {
    DB_NAME,
    SNIPPET_EXPIRY_MIN,
    SNIPPET_EXPIRY_MAX,
    SNIPPET_EXPIRY_DEFAULT,
    SNIPPET_CONTENT_MAX_LENGTH,
    SNIPPET_TITLE_MAX_LENGTH,
    SNIPPET_ID_LENGTH,
};
